//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NodeRedInstance) DeepCopyInto(out *NodeRedInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this NodeRedInstance.
func (in *NodeRedInstance) DeepCopy() *NodeRedInstance {
	if in == nil {
		return nil
	}
	out := new(NodeRedInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *NodeRedInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NodeRedInstanceList) DeepCopyInto(out *NodeRedInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeRedInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this NodeRedInstanceList.
func (in *NodeRedInstanceList) DeepCopy() *NodeRedInstanceList {
	if in == nil {
		return nil
	}
	out := new(NodeRedInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *NodeRedInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NodeRedInstanceSpec) DeepCopyInto(out *NodeRedInstanceSpec) {
	*out = *in
	out.OAuth = in.OAuth
	out.Image = in.Image
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of this NodeRedInstanceSpec.
func (in *NodeRedInstanceSpec) DeepCopy() *NodeRedInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRedInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NodeRedInstanceStatus) DeepCopyInto(out *NodeRedInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this NodeRedInstanceStatus.
func (in *NodeRedInstanceStatus) DeepCopy() *NodeRedInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRedInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *OAuthSpec) DeepCopyInto(out *OAuthSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of this OAuthSpec.
func (in *OAuthSpec) DeepCopy() *OAuthSpec {
	if in == nil {
		return nil
	}
	out := new(OAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of this ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}
